version: 2
updates:

# Go - root directory
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    ## group all dependencies with a k8s.io prefix into a single PR.
    groups:
      kubernetes:
        patterns: [ "k8s.io/*", "sigs.k8s.io/*" ]
      otel:
        patterns: ["go.opentelemetry.io/*"]
    commit-message:
      prefix: ":seedling:"
    labels:
      - "dependencies"

# Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ":seedling:"
    labels:
      - "dependencies"

# github-actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ":seedling:"
    labels:
      - "dependencies"
